# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hugo}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Wilson", "Barrett Little"]
  s.date = %q{2010-01-27}
  s.description = %q{A easy to understand DSL that makes it dirt simple to deploy to the cloud.}
  s.email = %q{tom@jackhq.com}
  s.executables = ["autospec", "ec2-gem-example.rb", "ec2-gem-profile.rb", "ec2sh", "edit_json.rb", "prettify_json.rb", "setup.rb", "spec"]
  s.files = [
    ".DS_Store",
     ".gitignore",
     "Gemfile",
     "Rakefile",
     "VERSION",
     "bin/autospec",
     "bin/ec2-gem-example.rb",
     "bin/ec2-gem-profile.rb",
     "bin/ec2sh",
     "bin/setup.rb",
     "bin/spec",
     "config/hugo.yml.example",
     "example/myhugo.rb",
     "lib/.DS_Store",
     "lib/hugo.old",
     "lib/hugo.rb",
     "lib/hugo/.DS_Store",
     "lib/hugo/app.rb",
     "lib/hugo/aws/ec2.rb",
     "lib/hugo/aws/elb.rb",
     "lib/hugo/aws/rds.rb",
     "lib/hugo/balancer.rb",
     "lib/hugo/cloud.rb",
     "lib/hugo/database.rb",
     "lib/hugo/mixin/params_validate.rb",
     "readme.md",
     "spec/.DS_Store",
     "spec/lib/hugo/app_spec.rb",
     "spec/lib/hugo/aws/ec2_spec.rb",
     "spec/lib/hugo/aws/elb_spec.rb",
     "spec/lib/hugo/aws/rds_spec.rb",
     "spec/lib/hugo/balancer_spec.rb",
     "spec/lib/hugo/database_spec.rb",
     "spec/lib/hugo_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "vendor/gems/cache/amazon-ec2-0.7.9.gem",
     "vendor/gems/cache/json-1.2.0.gem",
     "vendor/gems/cache/net-ssh-2.0.17.gem",
     "vendor/gems/cache/rspec-1.2.9.gem",
     "vendor/gems/cache/xml-simple-1.0.12.gem"
  ]
  s.homepage = %q{http://github.com/twilson63/hugo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Deploy Your Rack Apps to Cloud}
  s.test_files = [
    "spec/lib/hugo/app_spec.rb",
     "spec/lib/hugo/aws/ec2_spec.rb",
     "spec/lib/hugo/aws/elb_spec.rb",
     "spec/lib/hugo/aws/rds_spec.rb",
     "spec/lib/hugo/balancer_spec.rb",
     "spec/lib/hugo/database_spec.rb",
     "spec/lib/hugo_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

